#!/bin/bash

# Скрипт, который копирует файлы из директории $1 в директорию $2
#     а) Файлы, размер которых > $3 байт
#     б) Файлы, дата изменения которых старше, чем $3 часов от текущего момента.

# Старайся учитывать граничные случаи:
#  - существование директорий, файлов
#  - пробелы в именах
#  - пустые параметры скриптов
#  - и т.д. и т.п.

targer1=0
targer2=0

if [ -n "$1" ]; then
if [ -d "$1" ];  then targer1=1
else echo "первый параметр не директория"; fi
else echo "нет 1ого параметра" ; fi

if [ -n "$2" ]; then 
if [ -d "$2" ];  then targer2=1
else echo "второй параметр не директория"; fi
else echo "нет 2ого параметра"; fi

re='^[0-9]+$'

if [ -n "$3" ]; then
if ! [[ $3 =~ $re ]] ; then
   echo "error: Not a number" >&2; exit 1
fi
else echo "нет 3го параметра"; fi

# if [ -d $1 ] &&  [ -d $2 ] ; then 
if [ targer1 ] &&  [ targer2 ] ; then 
echo "2 папки"
cd $1
time=$(( $3 * 60 ))
for file in $(find . -type f -size "+$3c" -cmin +$time)
do
cp $file "../$2"
done
fi