#!/bin/bash

# в текстовом файле $1 находятся строки вида:
# <Строка_текста_без_пробелов>_<число1> current_offset: <число2> log_end_offset: <число3>
# Надо вывести все строки, содержащие строку $2, отсортированные в порядке возрастания по <число1> в формате
# <Строка_текста_без_пробелов>_<число1> lag: <число3-число2>

# Пример:
# Содержимое файла $1:
# hello_world_2 current_offset: 10 log_end_offset: 20
# world_hello_3 current_offset: 12 log_end_offset: 30
# hello_world_1 current_offset: 13 log_end_offset: 25

# Результат для ./script.sh "hello_world":
# hello_world_1 lag: 12  
# hello_world_2 lag: 10

if [ -f "$1" ];  then :
else exit 1 ; fi

if [ -n "$1" ]; then :
else exit1; fi

grep "$2" "$1" | sort  | awk '{print $1 " lag: " ( $5 - $3 )}'
